### ISSUE TITLE
-guild returning error.

### ISSUE THREAD

**Issue by chriscn** [chriscn/Dispixel#12]
```
0|Dispixel  | TypeError: (intermediate value).setTitle(...).setURL(...).color is not a function
0|Dispixel  |     at hypixeljs.getPlayer.byUuid (/home/pi/Dispixel/commands/guild.js:16:8)
0|Dispixel  |     at IncomingMessage.res.once (/home/pi/Dispixel/node_modules/hypixeljs/lib/api.js:97:5)
0|Dispixel  |     at Object.onceWrapper (events.js:313:30)
0|Dispixel  |     at emitNone (events.js:111:20)
0|Dispixel  |     at IncomingMessage.emit (events.js:208:7)
0|Dispixel  |     at endReadableNT (_stream_readable.js:1064:12)
0|Dispixel  |     at args.(anonymous function) (/usr/lib/node_modules/pm2/node_modules/event-loop-inspector/index.js:138:29)
0|Dispixel  |     at _combinedTickCallback (internal/process/next_tick.js:139:11)
0|Dispixel  |     at process._tickCallback (internal/process/next_tick.js:181:9)
0|Dispixel  | TypeError: Cannot read property 'displayname' of null
0|Dispixel  |     at hypixeljs.getPlayer.byUuid (/home/pi/Dispixel/commands/guild.js:11:28)
0|Dispixel  |     at handleError (/home/pi/Dispixel/node_modules/hypixeljs/lib/api.js:9:38)
0|Dispixel  |     at IncomingMessage.res.once (/home/pi/Dispixel/node_modules/hypixeljs/lib/api.js:99:5)
0|Dispixel  |     at Object.onceWrapper (events.js:313:30)
0|Dispixel  |     at emitNone (events.js:111:20)
0|Dispixel  |     at IncomingMessage.emit (events.js:208:7)
0|Dispixel  |     at endReadableNT (_stream_readable.js:1064:12)
0|Dispixel  |     at args.(anonymous function) (/usr/lib/node_modules/pm2/node_modules/event-loop-inspector/index.js:138:29)
0|Dispixel  |     at _combinedTickCallback (internal/process/next_tick.js:139:11)
0|Dispixel  |     at process._tickCallback (internal/process/next_tick.js:181:9)
```

**Comment by chriscn** [comment]
Fixed this because `player.displayname` returns null
